### ISSUE TITLE
hello mariya

### ISSUE THREAD

**Issue by shuxiaokai** [MariyaSha/groceriesList#1]
I need to learn this knowledge recently.Thanks

**Comment by MariyaSha** [comment]
Hi @shuxiaokai  :)
All project files are loaded! the app is fully functional now.
Files include:
1. **groceries_db.py** which is how I generated the Sqlite database for the project
  you can definitely edit it and insert your own values
2. **main.py** includes the Flask application, so when running it in your terminal:

FOR WINDOWS:
> cd path/to/project
> set flask_app=main
> set flask_env=development
> flask run

FOR LINUX:
> cd path/to/project
> export flask_app=main
> export flask_env=development
> flask run

The video tutorial will be posted very soon! I'm filming it tomorrow ;)
Good luck and I hope it helps!

**Comment by shuxiaokai** [comment]
Thank you so much for answering me,respect~~~~
